.PHONY: gen version test apptest build build-ipad screenshots icon clean

# The simulators the Makefile drives. Override on the command line to use
# your own clone: `make build SIM="my-clone"`.
SIM ?= iPhone 17
SIM_IPAD ?= iPad Pro 13-inch (M5)
# The two devices the store listing is shot on (see `screenshots`).
SHOT_SIM_PHONE ?= iPhone 17 Pro Max
SHOT_SIM_IPAD ?= $(SIM_IPAD)

# The build number App Store Connect sorts uploads by, from the commit
# count. xcodegen cannot shell out, and a target build setting would beat
# an xcconfig, so project.yml points the target's Debug and Release
# configurations at this file and leaves CURRENT_PROJECT_VERSION unset.
version:
	@printf '%s\n' \
	  '// Generated by `make gen` (see the Makefile'"'"'s version target) from' \
	  '// `git rev-list --count HEAD` — the build number App Store Connect sorts' \
	  '// uploads by. Committed so a bare `xcodegen generate` still resolves it;' \
	  '// the value is refreshed on every `make gen`, and the number that matters' \
	  '// is the one in the archive.' \
	  '//' \
	  '// MARKETING_VERSION lives in project.yml. A target-level build setting' \
	  '// beats an xcconfig, so CURRENT_PROJECT_VERSION must NOT be set there.' \
	  "CURRENT_PROJECT_VERSION = $$(git rev-list --count HEAD)" \
	  > App/Config/Version.xcconfig.new
	@cmp -s App/Config/Version.xcconfig.new App/Config/Version.xcconfig \
	  && rm App/Config/Version.xcconfig.new \
	  || mv App/Config/Version.xcconfig.new App/Config/Version.xcconfig

gen: version
	xcodegen generate

test:
	cd Packages/TycoonEngine && swift test
	cd Packages/TycoonContent && swift test
	cd Packages/TycoonSave && swift test
	cd Packages/PixelKit && swift test

# The App layer's own unit tests (see the StartupStudioTests target).
#
# The snapshot tests write their chrome PNGs into the app's own temporary
# directory: they run inside the simulator, and TEST_RUNNER_ settings do
# not reach an app-hosted unit test bundle. Collect them with
#   open "$$(xcrun simctl get_app_container booted com.alpsenel.startupstudio data)/tmp/startupstudio-previews"
apptest: gen
	xcodebuild -project StartupStudio.xcodeproj -scheme StartupStudio -destination "platform=iOS Simulator,name=$(SIM)" -derivedDataPath build test

build: gen
	xcodebuild -project StartupStudio.xcodeproj -scheme StartupStudio -destination "platform=iOS Simulator,name=$(SIM)" -derivedDataPath build build

# The same app on the iPad destination (iteration 7, R8). The iPad is the
# phone layout in a centred column — `AppRootView.maxColumnWidth` — not a
# second design, so this is a compile-and-look check, not a second target.
build-ipad: gen
	xcodebuild -project StartupStudio.xcodeproj -scheme StartupStudio -destination "platform=iOS Simulator,name=$(SIM_IPAD)" -derivedDataPath build build

# The App Store listing's screenshots (iteration 7, R8): one Debug build,
# installed on a 6.9" iPhone and a 13" iPad, launched once per shot with a
# bundled fixture save and the tab/route it is about, photographed with
# `simctl io screenshot` into docs/release/screenshots/<device>/.
#
# Override the devices with SHOT_SIM_PHONE / SHOT_SIM_IPAD; see
# scripts/screenshots.sh for the shot list and
# docs/release/screenshots.md for what to do with the output.
screenshots: gen
	SHOT_SIM_PHONE="$(SHOT_SIM_PHONE)" SHOT_SIM_IPAD="$(SHOT_SIM_IPAD)" scripts/screenshots.sh

# Regenerates the App Store icon from PixelKit sprites into
# App/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png.
icon:
	swift run --package-path Packages/IconGen IconGen

clean:
	rm -rf build
	rm -rf StartupStudio.xcodeproj
	cd Packages/TycoonEngine && swift package clean 2>/dev/null || true
	cd Packages/TycoonContent && swift package clean 2>/dev/null || true
	cd Packages/TycoonSave && swift package clean 2>/dev/null || true
	cd Packages/PixelKit && swift package clean 2>/dev/null || true
	cd Packages/IconGen && swift package clean 2>/dev/null || true
